[phases.setup]
nixPkgs = ["google-chrome-stable", "python311", "python311Packages.pip", "nodejs_22", "ffmpeg"]

[phases.install]
cmds = [
    "npm install",
    "pip install --user edge-tts"
]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "PATH=$PATH:/root/.local/bin npm start"