[phases.setup]
nixPkgs = ["chromium", "python311", "python311Packages.pip", "nodejs_23", "ffmpeg", "bash"]

[phases.install]
cmds = [
    "npm install",
    "chmod +x start.sh"
]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "./start.sh"