[phases.setup]
nixPkgs = ["google-chrome-stable", "python3", "python3Packages.pip", "ffmpeg"]

[phases.install]
cmds = ["npm install", "pip install edge-tts"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm start"